### ISSUE TITLE
 uncaughtException TypeError: params.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by ElusiveMind** [ProboCI/probo-request-logger#3]
On the open source project, I started seeing errors once PR https://github.com/ProboCI/probo-request-logger/pull/2 was merged to probo-request-logger

After updating, I am getting the following in my probo-cm error logs:
```
Oct 24 14:42:28 localhost probo-cm: uncaughtException TypeError: params.hasOwnProperty is not a function
Oct 24 14:42:28 localhost probo-cm: at Server.<anonymous> (/opt/probo/probo/node_modules/probo-request-logger/index.js:39:20)
Oct 24 14:42:28 localhost probo-cm: at next (/opt/probo/probo/node_modules/restify/lib/server.js:745:30)
Oct 24 14:42:28 localhost probo-cm: at f (/opt/probo/probo/node_modules/once/once.js:25:25)
Oct 24 14:42:28 localhost probo-cm: at Server.parseQueryString (/opt/probo/probo/node_modules/restify/lib/plugins/query.js:39:17)
Oct 24 14:42:28 localhost probo-cm: at next (/opt/probo/probo/node_modules/restify/lib/server.js:745:30)
Oct 24 14:42:28 localhost probo-cm: at f (/opt/probo/probo/node_modules/once/once.js:25:25)
Oct 24 14:42:28 localhost probo-cm: at Server.parseBody (/opt/probo/probo/node_modules/restify/lib/plugins/body_parser.js:47:13)
Oct 24 14:42:28 localhost probo-cm: at next (/opt/probo/probo/node_modules/restify/lib/server.js:745:30)
Oct 24 14:42:28 localhost probo-cm: at f (/opt/probo/probo/node_modules/once/once.js:25:25)
Oct 24 14:42:28 localhost probo-cm: at Server.readBody (/opt/probo/probo/node_modules/restify/lib/plugins/body_reader.js:55:13)
Oct 24 14:42:28 localhost probo-cm: at next (/opt/probo/probo/node_modules/restify/lib/server.js:745:30)
Oct 24 14:42:28 localhost probo-cm: at f (/opt/probo/probo/node_modules/once/once.js:25:25)
Oct 24 14:42:28 localhost probo-cm: at Server.parseAccept (/opt/probo/probo/node_modules/restify/lib/plugins/accept.js:37:13)
Oct 24 14:42:28 localhost probo-cm: at Domain.next (/opt/probo/probo/node_modules/restify/lib/server.js:745:30)
Oct 24 14:42:28 localhost probo-cm: at Domain.f (/opt/probo/probo/node_modules/once/once.js:25:25)
Oct 24 14:42:28 localhost probo-cm: at Domain.run (domain.js:221:14)
```

Commenting out lines 33-44 resolved the issue, but this is not a fix. Requesting assistance and will attempt to further triage myself.

**Comment by ElusiveMind** [comment]
Pull request #4 is available for potentially fixing this issue.
